version: 2
references:
  dirs:
    etl_feeds: &etl_feeds_dir
      ~/etl-feeds
  environment:
    global: &global_environment
      - DEPLOY_BRANCHES: master,staging,production
jobs:
  build:
    docker:
      - image: circleci/python:2.7
    environment: *global_environment
    working_directory: *etl_feeds_dir
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python -m virtualenv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            nosetests -v tests/test_feeds.py --nocapture

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - store_artifacts:
          path: test-reports
          destination: test-reports
  deploy-dev:
    docker:
      - image: circleci/python:2.7
    working_directory: *etl_feeds_dir  
    environment:
      S3_ENV: dev
      S3_ETL_FEEDS_BUCKET: etl-feeds-test
      GZIP: -9
      BACKUP_MAX_DAYS: 60
    steps:
      - checkout
      - run:
          name: Backup existing data
          command: |
            pip install awscli --upgrade --user
            PATH=${PATH}:/home/circleci/.local/bin
            CURRENTDATE=$(date -u +"%Y_%m_%d_%H_%M_%S")
            mkdir archives
            aws s3 sync s3://$S3_ETL_FEEDS_BUCKET/$S3_ENV/archives ./archives --region us-west-2
            bash ./remove_stale_feed_backups.sh $BACKUP_MAX_DAYS
            mkdir mkdir $CURRENTDATE
            aws s3 sync s3://$S3_ETL_FEEDS_BUCKET/$S3_ENV/data ./$CURRENTDATE --region us-west-2
            tar -zcvf ./archives/$CURRENTDATE.tar.gz ./$CURRENTDATE
            aws s3 sync ./archives s3://$S3_ETL_FEEDS_BUCKET/$S3_ENV/archives --region us-west-2 --delete
            rm -r ./$CURRENTDATE
            rm -r ./archives
      - run:
          name: Deploy if tests pass and branch is Master
          command: |
            pip install awscli --upgrade --user
            PATH=${PATH}:/home/circleci/.local/bin
            aws s3 sync ./data s3://$S3_ETL_FEEDS_BUCKET/$S3_ENV/data --region us-west-2 --delete            
  deploy-stage:
    docker:
      - image: circleci/python:2.7
    working_directory: *etl_feeds_dir
    environment:
      S3_ENV: staging
      S3_ETL_FEEDS_BUCKET: etl-feeds-test
      GZIP: -9
      BACKUP_MAX_DAYS: 60
    steps:
      - checkout
      - run:
          name: Backup existing data
          command: |
            pip install awscli --upgrade --user
            PATH=${PATH}:/home/circleci/.local/bin
            CURRENTDATE=$(date -u +"%Y_%m_%d_%H_%M_%S")
            mkdir archives
            aws s3 sync s3://$S3_ETL_FEEDS_BUCKET/$S3_ENV/archives ./archives --region us-west-2
            bash ./remove_stale_feed_backups.sh $BACKUP_MAX_DAYS         
            mkdir mkdir $CURRENTDATE
            aws s3 sync s3://$S3_ETL_FEEDS_BUCKET/$S3_ENV/data ./$CURRENTDATE --region us-west-2
            tar -zcvf ./archives/$CURRENTDATE.tar.gz ./$CURRENTDATE
            aws s3 sync ./archives s3://$S3_ETL_FEEDS_BUCKET/$S3_ENV/archives --region us-west-2
            rm -r ./$CURRENTDATE
            rm -r ./archives
      - run:
          name: Deploy if tests pass and branch is Staging
          command: |
            pip install awscli --upgrade --user
            PATH=${PATH}:/home/circleci/.local/bin
            aws s3 sync ./data s3://$S3_ETL_FEEDS_BUCKET/$S3_ENV/data --region us-west-2 --delete
  deploy-prod:
    docker:
      - image: circleci/python:2.7
    working_directory: *etl_feeds_dir
    environment:
      S3_ENV: prod
      S3_ETL_FEEDS_BUCKET: etl-feeds-test
      GZIP: -9
      BACKUP_MAX_DAYS: 60
    steps:
      - checkout
      - run:
          name: Backup existing data
          command: |
            pip install awscli --upgrade --user
            PATH=${PATH}:/home/circleci/.local/bin
            CURRENTDATE=$(date -u +"%Y_%m_%d_%H_%M_%S")
            mkdir archives
            aws s3 sync s3://$S3_ETL_FEEDS_BUCKET/$S3_ENV/archives ./archives --region us-west-2
            bash ./remove_stale_feed_backups.sh $BACKUP_MAX_DAYS
            mkdir mkdir $CURRENTDATE
            aws s3 sync s3://$S3_ETL_FEEDS_BUCKET/$S3_ENV/data ./$CURRENTDATE --region us-west-2
            tar -zcvf ./archives/$CURRENTDATE.tar.gz ./$CURRENTDATE
            aws s3 sync ./archives s3://$S3_ETL_FEEDS_BUCKET/$S3_ENV/archives --region us-west-2 --delete
            rm -r ./$CURRENTDATE
            rm -r ./archives
      - run:
          name: Deploy if tests pass and branch is Production
          command: |
            pip install awscli --upgrade --user
            PATH=${PATH}:/home/circleci/.local/bin
            aws s3 sync ./data s3://$S3_ETL_FEEDS_BUCKET/$S3_ENV/data --region us-west-2 --delete
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy-dev:
          requires:
            - build
          filters:
            branches:
              only: master
      - deploy-stage:
          requires:
            - build
          filters:
            branches:
              only: staging
      - deploy-prod:
          requires:
            - build
          filters:
            branches:
              only: production